name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app


jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-08-11-a
      - name: Bootstrap
        run: make bootstrap    
      - name: Build
        run: make build
      - name: Lint
        run: make lint  
      - name: Run tests
        run: make test